import 'dart:io';

import 'package:basalt/basalt.dart';
import 'package:basalt/tooling.dart';

/// Emits a Dart `schema.dart` from an introspected schema — **tables and
/// columns only** (the `generate-schema` analog). Data classes are intentionally
/// not generated; users define those themselves (and, later, with `@Queryable`).
///
/// Column types come from [typeOverrides] when configured (see the `types:`
/// block of `basalt.yaml`), otherwise from the built-in [ColumnType] mapping.
///
/// {@category migrations}
final class SchemaGenerator {
  const SchemaGenerator({
    this.typeOverrides = const SchemaTypeOverrides.empty(),
  });

  /// Config-level overrides applied to each column before the built-in mapping.
  final SchemaTypeOverrides typeOverrides;

  static const _basaltImport = 'package:basalt/basalt.dart';

  String generate(List<IntrospectedTable> tables) {
    final pkByTable = _primaryKeysByTable(tables);
    final columnsByKey = {
      for (final t in tables)
        for (final c in t.columns) '${t.name}.${c.name}': c,
    };

    // Column declarations are emitted into a body buffer first so any imports
    // that overrides pull in can be written above the classes.
    final imports = <String>{};
    final body = StringBuffer();
    for (final table in tables) {
      final cls = _pascal(table.name);
      body
        ..writeln('final class $cls extends TableRef<$cls> {')
        ..writeln("  const $cls._() : super('${table.name}');")
        ..writeln()
        ..writeln('  static const table = $cls._();')
        ..writeln();
      for (final column in table.columns) {
        body.writeln(
          _columnDecl(
              table.name, cls, column, pkByTable, columnsByKey, imports),
        );
      }
      final fields = table.columns.map((c) => _camel(c.name)).join(', ');
      body
        ..writeln()
        ..writeln('  @override')
        ..writeln(
          '  List<TableColumn<Object?, Object?>> get columns => '
          'const [$fields];',
        )
        ..writeln('}')
        ..writeln();
    }

    final out = StringBuffer()
      ..writeln(
        '// GENERATED by `basalt generate-schema`. Do not edit by hand.',
      )
      ..writeln("import '$_basaltImport';");
    for (final uri in imports.toList()..sort()) {
      out.writeln("import '$uri';");
    }
    out
      ..writeln()
      ..write(body);
    return '${out.toString().trimRight()}\n';
  }

  Map<String, String> _primaryKeysByTable(List<IntrospectedTable> tables) {
    return {
      for (final t in tables)
        t.name: t.columns
            .firstWhere((c) => c.isPrimaryKey, orElse: () => t.columns.first)
            .name,
    };
  }

  String _columnDecl(
    String tableName,
    String cls,
    IntrospectedColumn column,
    Map<String, String> pkByTable,
    Map<String, IntrospectedColumn> columnsByKey,
    Set<String> imports,
  ) {
    final field = _camel(column.name);
    _checkReservedName(tableName, column.name, field);
    final (dartType, sqlType, import) = _resolveType(tableName, column);
    if (import case final uri? when uri.isNotEmpty && uri != _basaltImport) {
      imports.add(uri);
    }
    if (column.isNullable && !dartType.endsWith('?')) {
      stderr.writeln(
        'Warning: column $tableName.${column.name} is nullable but its type '
        "override '$dartType' is not — add a `nullable:` variant (or a nullable "
        'dart_type) if it should allow NULL.',
      );
    }
    if (column.foreignKey case final fk?) {
      final targetCls = _pascal(fk.table);
      final targetColumn =
          fk.column.isNotEmpty ? fk.column : (pkByTable[fk.table] ?? 'id');
      _checkRefAgreement(
        tableName,
        column,
        dartType,
        fk.table,
        targetColumn,
        columnsByKey,
      );
      return _decl(
        field,
        'Ref<$dartType, $cls, $targetCls>',
        column.name,
        sqlType,
        references: '$targetCls.${_camel(targetColumn)}',
      );
    }
    if (column.isPrimaryKey) {
      return _decl(field, 'PrimaryKey<$dartType, $cls>', column.name, sqlType);
    }
    return _decl(field, 'ValueColumn<$dartType, $cls>', column.name, sqlType);
  }

  /// One `static const` column declaration, one argument per line with a
  /// trailing comma — the split survives `dart format`, so generated files
  /// stay diff-stable no matter how long the type arguments get.
  String _decl(
    String field,
    String constructor,
    String columnName,
    String sqlType, {
    String? references,
  }) {
    final buffer = StringBuffer()
      ..writeln('  static const $field = $constructor(')
      ..writeln('    table,')
      ..writeln("    '$columnName',")
      ..writeln('    $sqlType,');
    if (references case final target?) {
      buffer.writeln('    references: $target,');
    }
    buffer.write('  );');
    return buffer.toString();
  }

  /// Resolves a column to `(dartType, sqlTypeExpr, import?)` — [typeOverrides]
  /// first, then the built-in [_mapType]. Pure: no imports/warnings side effects
  /// (so it is safe to call for a `Ref` target during agreement checks).
  (String, String, String?) _resolveType(
    String tableName,
    IntrospectedColumn column,
  ) {
    if (typeOverrides.resolve(tableName, column) case final override?) {
      return (override.dartType, override.sqlType, override.import);
    }
    final (dartType, sqlType) = _mapType(column.type, column.isNullable);
    return (dartType, sqlType, null);
  }

  /// Members every marker inherits from `TableRef`/`Object` (plus its own
  /// `table` singleton) — a column whose camelCase field name lands on one of
  /// these cannot be emitted as a `static const`.
  static const _reservedFieldNames = {
    'table',
    'tableName',
    'alias',
    'columns',
    'col',
    'aliased',
    'hashCode',
    'runtimeType',
    'toString',
    'noSuchMethod',
  };

  /// Table markers extend `TableRef`, so a static column field may not shadow
  /// an inherited instance member (`CONFLICTING_STATIC_AND_INSTANCE`) — fail
  /// with a clear message instead of emitting code that won't compile.
  void _checkReservedName(String tableName, String columnName, String field) {
    if (!_reservedFieldNames.contains(field)) return;
    throw StateError(
      'Column $tableName.$columnName maps to the field name `$field`, which '
      'collides with a `TableRef` member inherited by the generated table '
      'class. Rename the column, or map it manually.',
    );
  }

  /// A `Ref<T, …>` and the `PrimaryKey<T, …>` it references must share `T`.
  /// Overrides can break that if one side is customized and the other isn't, so
  /// resolve the target column the same way and fail with a clear message rather
  /// than emit code that won't compile. Nullability is ignored (a nullable FK
  /// legitimately references a non-null PK).
  void _checkRefAgreement(
    String tableName,
    IntrospectedColumn column,
    String dartType,
    String targetTable,
    String targetColumn,
    Map<String, IntrospectedColumn> columnsByKey,
  ) {
    final target = columnsByKey['$targetTable.$targetColumn'];
    if (target == null) return; // target not introspected — nothing to check
    final (targetType, _, _) = _resolveType(targetTable, target);
    if (_nonNull(dartType) != _nonNull(targetType)) {
      throw StateError(
        'Foreign key $tableName.${column.name} resolves to `$dartType` but its '
        'target $targetTable.$targetColumn resolves to `$targetType`; a Ref and '
        'its referenced PrimaryKey must share the key type. Override both, or '
        'neither.',
      );
    }
  }

  String _nonNull(String type) =>
      type.endsWith('?') ? type.substring(0, type.length - 1) : type;

  /// Maps a canonical [ColumnType] to a Dart type + `SqlType` subclass —
  /// dialect-agnostic, since each backend already normalized its native types
  /// during introspection.
  (String, String) _mapType(ColumnType type, bool nullable) {
    final (String base, String cls) = switch (type) {
      ColumnType.integer => ('int', 'IntSqlType'),
      ColumnType.text => ('String', 'StringSqlType'),
      ColumnType.real => ('double', 'DoubleSqlType'),
      ColumnType.boolean => ('bool', 'BooleanSqlType'),
      ColumnType.blob => ('List<int>', 'BlobSqlType'),
      ColumnType.dateTime => ('DateTime', 'DateTimeSqlType'),
    };
    // No `const` prefix: the column is emitted into a `static const` field, so
    // the constructor is already a const context — an explicit `const` here
    // trips `unnecessary_const` in lint-enabled projects (e.g. flutter_lints).
    return nullable ? ('$base?', 'NullableSqlType($cls())') : (base, '$cls()');
  }

  String _pascal(String s) => s
      .split('_')
      .where((p) => p.isNotEmpty)
      .map((p) => '${p[0].toUpperCase()}${p.substring(1)}')
      .join();

  String _camel(String s) {
    final pascal = _pascal(s);
    return pascal.isEmpty
        ? pascal
        : '${pascal[0].toLowerCase()}${pascal.substring(1)}';
  }
}
