import 'dart:io';

import 'package:basalt/basalt.dart';
import 'package:basalt/tooling.dart';

/// Emits a Dart `schema.dart` from an introspected schema — **tables and
/// columns only** (the `generate-schema` analog). Data classes are intentionally
/// not generated; users define those themselves (and, later, with `@Queryable`).
///
/// Column types come from [typeOverrides] when configured (see the `types:`
/// block of `basalt.yaml`), otherwise from the built-in [ColumnType] mapping.
///
/// {@category migrations}
final class SchemaGenerator {
  const SchemaGenerator({
    this.typeOverrides = const SchemaTypeOverrides.empty(),
  });

  /// Config-level overrides applied to each column before the built-in mapping.
  final SchemaTypeOverrides typeOverrides;

  static const _basaltImport = 'package:basalt/basalt.dart';

  String generate(List<IntrospectedTable> tables) {
    final pkByTable = _primaryKeysByTable(tables);
    final columnsByKey = {
      for (final t in tables)
        for (final c in t.columns) '${t.name}.${c.name}': c,
    };

    // Column declarations are emitted into a body buffer first so any imports
    // that overrides pull in can be written above the classes.
    final imports = <String>{};
    final body = StringBuffer();
    for (final table in tables) {
      final cls = _pascal(table.name);
      body.writeln('abstract final class $cls {');
      for (final column in table.columns) {
        body.writeln(
          '  ${_columnDecl(table.name, cls, column, pkByTable, columnsByKey, imports)}',
        );
      }
      final fields = table.columns.map((c) => _camel(c.name)).join(', ');
      body.writeln(
        "  static const table = TableRef<$cls>('${table.name}', [$fields]);",
      );
      body
        ..writeln('}')
        ..writeln();
    }

    final out = StringBuffer()
      ..writeln(
        '// GENERATED by `basalt generate-schema`. Do not edit by hand.',
      )
      ..writeln("import '$_basaltImport';");
    for (final uri in imports.toList()..sort()) {
      out.writeln("import '$uri';");
    }
    out
      ..writeln()
      ..write(body);
    return '${out.toString().trimRight()}\n';
  }

  Map<String, String> _primaryKeysByTable(List<IntrospectedTable> tables) {
    return {
      for (final t in tables)
        t.name: t.columns
            .firstWhere((c) => c.isPrimaryKey, orElse: () => t.columns.first)
            .name,
    };
  }

  String _columnDecl(
    String tableName,
    String cls,
    IntrospectedColumn column,
    Map<String, String> pkByTable,
    Map<String, IntrospectedColumn> columnsByKey,
    Set<String> imports,
  ) {
    final field = _camel(column.name);
    final (dartType, sqlType, import) = _resolveType(tableName, column);
    if (import case final uri? when uri.isNotEmpty && uri != _basaltImport) {
      imports.add(uri);
    }
    if (column.isNullable && !dartType.endsWith('?')) {
      stderr.writeln(
        'Warning: column $tableName.${column.name} is nullable but its type '
        "override '$dartType' is not — add a `nullable:` variant (or a nullable "
        'dart_type) if it should allow NULL.',
      );
    }
    final args = "'$tableName', '${column.name}', $sqlType";

    if (column.foreignKey case final fk?) {
      final targetCls = _pascal(fk.table);
      final targetColumn =
          fk.column.isNotEmpty ? fk.column : (pkByTable[fk.table] ?? 'id');
      _checkRefAgreement(
        tableName,
        column,
        dartType,
        fk.table,
        targetColumn,
        columnsByKey,
      );
      return 'static const $field = '
          'Ref<$dartType, $cls, $targetCls>($args, references: $targetCls.${_camel(targetColumn)});';
    }
    if (column.isPrimaryKey) {
      return 'static const $field = PrimaryKey<$dartType, $cls>($args);';
    }
    return 'static const $field = ValueColumn<$dartType, $cls>($args);';
  }

  /// Resolves a column to `(dartType, sqlTypeExpr, import?)` — [typeOverrides]
  /// first, then the built-in [_mapType]. Pure: no imports/warnings side effects
  /// (so it is safe to call for a `Ref` target during agreement checks).
  (String, String, String?) _resolveType(
    String tableName,
    IntrospectedColumn column,
  ) {
    if (typeOverrides.resolve(tableName, column) case final override?) {
      return (override.dartType, override.sqlType, override.import);
    }
    final (dartType, sqlType) = _mapType(column.type, column.isNullable);
    return (dartType, sqlType, null);
  }

  /// A `Ref<T, …>` and the `PrimaryKey<T, …>` it references must share `T`.
  /// Overrides can break that if one side is customized and the other isn't, so
  /// resolve the target column the same way and fail with a clear message rather
  /// than emit code that won't compile. Nullability is ignored (a nullable FK
  /// legitimately references a non-null PK).
  void _checkRefAgreement(
    String tableName,
    IntrospectedColumn column,
    String dartType,
    String targetTable,
    String targetColumn,
    Map<String, IntrospectedColumn> columnsByKey,
  ) {
    final target = columnsByKey['$targetTable.$targetColumn'];
    if (target == null) return; // target not introspected — nothing to check
    final (targetType, _, _) = _resolveType(targetTable, target);
    if (_nonNull(dartType) != _nonNull(targetType)) {
      throw StateError(
        'Foreign key $tableName.${column.name} resolves to `$dartType` but its '
        'target $targetTable.$targetColumn resolves to `$targetType`; a Ref and '
        'its referenced PrimaryKey must share the key type. Override both, or '
        'neither.',
      );
    }
  }

  String _nonNull(String type) =>
      type.endsWith('?') ? type.substring(0, type.length - 1) : type;

  /// Maps a canonical [ColumnType] to a Dart type + `SqlType` subclass —
  /// dialect-agnostic, since each backend already normalized its native types
  /// during introspection.
  (String, String) _mapType(ColumnType type, bool nullable) {
    final (String base, String cls) = switch (type) {
      ColumnType.integer => ('int', 'IntSqlType'),
      ColumnType.text => ('String', 'StringSqlType'),
      ColumnType.real => ('double', 'DoubleSqlType'),
      ColumnType.boolean => ('bool', 'BooleanSqlType'),
      ColumnType.blob => ('List<int>', 'BlobSqlType'),
      ColumnType.dateTime => ('DateTime', 'DateTimeSqlType'),
    };
    // No `const` prefix: the column is emitted into a `static const` field, so
    // the constructor is already a const context — an explicit `const` here
    // trips `unnecessary_const` in lint-enabled projects (e.g. flutter_lints).
    return nullable
        ? ('$base?', 'NullableSqlType($cls())')
        : (base, '$cls()');
  }

  String _pascal(String s) => s
      .split('_')
      .where((p) => p.isNotEmpty)
      .map((p) => '${p[0].toUpperCase()}${p.substring(1)}')
      .join();

  String _camel(String s) {
    final pascal = _pascal(s);
    return pascal.isEmpty
        ? pascal
        : '${pascal[0].toLowerCase()}${pascal.substring(1)}';
  }
}
