import 'package:basalt/basalt.dart';

/// Emits a Dart `schema.dart` from an introspected schema — **tables and
/// columns only** (the `generate-schema` analog). Data classes are intentionally
/// not generated; users define those themselves (and, later, with `@Queryable`).
///
/// {@category migrations}
final class SchemaGenerator {
  const SchemaGenerator();

  String generate(List<IntrospectedTable> tables) {
    final pkByTable = _primaryKeysByTable(tables);

    final out = StringBuffer()
      ..writeln(
          '// GENERATED by `basalt generate-schema`. Do not edit by hand.',)
      ..writeln("import 'package:basalt/basalt.dart';")
      ..writeln();

    for (final table in tables) {
      final cls = _pascal(table.name);
      out.writeln('abstract final class $cls {');
      for (final column in table.columns) {
        out.writeln('  ${_columnDecl(table.name, cls, column, pkByTable)}');
      }
      final fields = table.columns.map((c) => _camel(c.name)).join(', ');
      out.writeln(
          "  static const table = TableRef<$cls>('${table.name}', [$fields]);",);
      out
        ..writeln('}')
        ..writeln();
    }
    return '${out.toString().trimRight()}\n';
  }

  Map<String, String> _primaryKeysByTable(List<IntrospectedTable> tables) {
    return {
      for (final t in tables)
        t.name: t.columns
            .firstWhere((c) => c.isPrimaryKey, orElse: () => t.columns.first)
            .name,
    };
  }

  String _columnDecl(
    String tableName,
    String cls,
    IntrospectedColumn column,
    Map<String, String> pkByTable,
  ) {
    final field = _camel(column.name);
    final (dartType, sqlType) = _mapType(column.type, column.isNullable);
    final args = "'$tableName', '${column.name}', $sqlType";

    if (column.foreignKey case final fk?) {
      final targetCls = _pascal(fk.table);
      final targetColumn =
          fk.column.isNotEmpty ? fk.column : (pkByTable[fk.table] ?? 'id');
      return 'static const $field = '
          'Ref<$dartType, $cls, $targetCls>($args, references: $targetCls.${_camel(targetColumn)});';
    }
    if (column.isPrimaryKey) {
      return 'static const $field = PrimaryKey<$dartType, $cls>($args);';
    }
    return 'static const $field = ValueColumn<$dartType, $cls>($args);';
  }

  /// Maps a canonical [ColumnType] to a Dart type + `SqlType` — dialect-agnostic,
  /// since each backend already normalized its native types during introspection.
  (String, String) _mapType(ColumnType type, bool nullable) {
    final (String base, String sql) = switch (type) {
      ColumnType.integer => ('int', 'integer'),
      ColumnType.text => ('String', 'text'),
      ColumnType.real => ('double', 'real'),
      ColumnType.boolean => ('bool', 'boolean'),
      ColumnType.blob => ('List<int>', 'blob'),
      ColumnType.dateTime => ('DateTime', 'dateTime'),
    };
    return nullable
        ? ('$base?', 'SqlType.${sql}OrNull')
        : (base, 'SqlType.$sql');
  }

  String _pascal(String s) => s
      .split('_')
      .where((p) => p.isNotEmpty)
      .map((p) => '${p[0].toUpperCase()}${p.substring(1)}')
      .join();

  String _camel(String s) {
    final pascal = _pascal(s);
    return pascal.isEmpty
        ? pascal
        : '${pascal[0].toLowerCase()}${pascal.substring(1)}';
  }
}
