name: root
description: Monorepo for Basalt Dart
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0

workspace:
  - packages/basalt
  - packages/basalt_sqlite
  - packages/basalt_cli
  - packages/basalt_codegen
  - packages/basalt_postgres
  - example
