import 'dart:io';

import 'package:basalt_cli/basalt_cli.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('BackendResolver', () {
    late Directory tmp;
    setUp(() {
      tmp = Directory.systemTemp.createTempSync('basalt_bootstrap_test');
      addTearDown(() => tmp.deleteSync(recursive: true));
    });

    String write(String yaml) {
      final path = p.join(tmp.path, 'basalt.yaml');
      File(path).writeAsStringSync(yaml);
      return path;
    }

    test('reads an explicit backend:', () {
      final path = write('backend: my_backend\ndatabase: {foo: 1}\n');
      expect(
        const BackendResolver().resolve(path, environment: {}),
        'my_backend',
      );
    });

    test('throws when backend: is omitted (no default)', () {
      final path = write('database: {path: x.db}\n');
      expect(
        () => const BackendResolver().resolve(path, environment: {}),
        throwsA(
          isStateError.having(
            (e) => e.message,
            'message',
            allOf(
              contains('No backend configured'),
              contains('backend: basalt_sqlite'),
            ),
          ),
        ),
      );
    });

    test('a missing config file throws', () {
      expect(
        () => const BackendResolver()
            .resolve(p.join(tmp.path, 'nope.yaml'), environment: {}),
        throwsStateError,
      );
    });

    test('suggests basalt_postgres when database.url looks like Postgres', () {
      final path = write('database: {url: postgres://localhost/app}\n');
      expect(
        () => const BackendResolver().resolve(path, environment: {}),
        throwsA(
          isStateError.having(
            (e) => e.message,
            'message',
            contains('backend: basalt_postgres'),
          ),
        ),
      );
    });

    test('the Postgres suggestion also reads DATABASE_URL', () {
      final path = write('database: {path: x.db}\n');
      expect(
        () => const BackendResolver().resolve(
          path,
          environment: {'DATABASE_URL': 'postgresql://localhost/app'},
        ),
        throwsA(
          isStateError.having(
            (e) => e.message,
            'message',
            contains('backend: basalt_postgres'),
          ),
        ),
      );
    });

    test('an explicit backend: is used verbatim', () {
      final path = write(
        'backend: basalt_postgres\ndatabase: {url: postgres://localhost/a}\n',
      );
      expect(
        const BackendResolver().resolve(path, environment: {}),
        'basalt_postgres',
      );
    });

    test('rejects an invalid backend: value', () {
      final path = write('backend: "Not A Package"\n');
      expect(
        () => const BackendResolver().resolve(path, environment: {}),
        throwsStateError,
      );
    });
  });

  group('EntrypointGenerator', () {
    test('emits an entrypoint importing the backend adapter', () {
      final source =
          const EntrypointGenerator().generate(backendPackage: 'basalt_sqlite');
      expect(source, contains('// GENERATED by the basalt CLI'));
      expect(
        source,
        contains("import 'package:basalt_cli/basalt_cli.dart' as cli;"),
      );
      expect(
        source,
        contains("import 'package:basalt_sqlite/adapter.dart' as backend;"),
      );
      expect(
        source,
        contains('cli.runBasalt(args, adapter: backend.adapter)'),
      );
    });

    test('is deterministic', () {
      const generator = EntrypointGenerator();
      expect(
        generator.generate(backendPackage: 'x'),
        generator.generate(backendPackage: 'x'),
      );
    });
  });

  group('Bootstrapper', () {
    test(
      'writes the entrypoint once and reuses it until the fingerprint changes',
      () async {
        // Run against the CLI package itself: its package graph contains
        // basalt_sqlite (a dev dependency), so bootstrap succeeds without a
        // fake package_config. `--help` avoids touching a database; a temp
        // config supplies the now-required `backend:`.
        final tmp = Directory.systemTemp.createTempSync('basalt_boot_e2e');
        addTearDown(() => tmp.deleteSync(recursive: true));
        final configPath = p.join(tmp.path, 'basalt.yaml');
        File(configPath).writeAsStringSync('backend: basalt_sqlite\n');
        final args = ['--config', configPath, '--help'];

        final previous = Directory.current;
        Directory.current = Directory(p.current);
        addTearDown(() => Directory.current = previous);

        final code = await const Bootstrapper().run(args);
        expect(code, 0);

        final entrypoint = _workspaceFile('basalt/entrypoint.dart');
        final fingerprint = _workspaceFile('basalt/entrypoint.fingerprint');
        expect(entrypoint.existsSync(), isTrue);
        expect(fingerprint.existsSync(), isTrue);
        expect(
          entrypoint.readAsStringSync(),
          contains("import 'package:basalt_sqlite/adapter.dart'"),
        );

        // A second run with an unchanged fingerprint must not rewrite.
        final firstWrite = entrypoint.lastModifiedSync();
        final second = await const Bootstrapper().run(args);
        expect(second, 0);
        expect(entrypoint.lastModifiedSync(), firstWrite);

        // A fingerprint change forces a rewrite.
        fingerprint.writeAsStringSync('stale');
        final third = await const Bootstrapper().run(args);
        expect(third, 0);
        expect(fingerprint.readAsStringSync(), isNot('stale'));
      },
      timeout: const Timeout(Duration(minutes: 2)),
      tags: 'bootstrap-e2e',
    );

    test('errors clearly when the backend package is missing', () async {
      // `backend: not_a_real_package` is not in this package's graph.
      final tmp = Directory.systemTemp.createTempSync('basalt_boot_missing');
      addTearDown(() => tmp.deleteSync(recursive: true));
      final configPath = p.join(tmp.path, 'basalt.yaml');
      File(configPath).writeAsStringSync(
        'backend: not_a_real_package\ndatabase: {foo: 1}\n',
      );

      expect(
        () => const Bootstrapper().run(['--config', configPath, '--help']),
        throwsA(
          isStateError.having(
            (e) => e.message,
            'message',
            contains('dev_dependencies'),
          ),
        ),
      );
    });
  });
}

/// Resolves a path under the nearest `.dart_tool` (walking up from cwd, the
/// same way the bootstrapper does — in this workspace that's the repo root).
File _workspaceFile(String relative) {
  var dir = Directory.current.absolute;
  while (true) {
    final dartTool = Directory(p.join(dir.path, '.dart_tool'));
    if (dartTool.existsSync() &&
        File(p.join(dartTool.path, 'package_config.json')).existsSync()) {
      return File(p.join(dartTool.path, relative));
    }
    dir = dir.parent;
  }
}
