import 'dart:io';

import 'package:basalt/basalt.dart';
import 'package:basalt_cli/basalt_cli.dart';
import 'package:basalt_sqlite/adapter.dart';
import 'package:basalt_sqlite/basalt_sqlite.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

/// The exact multi-line declaration `SchemaGenerator` emits for one column.
String columnDecl(
  String field,
  String constructor,
  String column,
  String sqlType, {
  String? references,
}) =>
    '  static const $field = $constructor(\n'
    '    table,\n'
    "    '$column',\n"
    '    $sqlType,\n'
    '${references == null ? '' : '    references: $references,\n'}'
    '  );';

void main() {
  late SqliteConnection db;

  setUp(() async {
    db = SqliteConnection.memory();
    await db.executeSql('CREATE TABLE users ('
        'id INTEGER NOT NULL PRIMARY KEY, '
        'name TEXT NOT NULL, '
        'bio TEXT, ' // nullable
        'age INTEGER NOT NULL)');
    await db.executeSql('CREATE TABLE posts ('
        'id INTEGER NOT NULL PRIMARY KEY, '
        'author_id INTEGER NOT NULL REFERENCES users(id), '
        'title TEXT NOT NULL)');
  });

  tearDown(() => db.close());

  test('introspect reads tables, columns, nullability, pk and fks', () async {
    final tables = await db.introspect();
    expect(tables.map((t) => t.name), ['posts', 'users']); // sorted

    final users = tables.firstWhere((t) => t.name == 'users');
    final id = users.columns.firstWhere((c) => c.name == 'id');
    expect(id.isPrimaryKey, isTrue);
    expect(id.isNullable, isFalse);
    final bio = users.columns.firstWhere((c) => c.name == 'bio');
    expect(bio.isNullable, isTrue);

    final posts = tables.firstWhere((t) => t.name == 'posts');
    final authorId = posts.columns.firstWhere((c) => c.name == 'author_id');
    expect(authorId.foreignKey?.table, 'users');
    expect(authorId.foreignKey?.column, 'id');
  });

  test('generateSchema emits tables-only Dart (no data classes)', () async {
    final source = const SchemaGenerator().generate(await db.introspect());

    expect(source, contains("import 'package:basalt/basalt.dart';"));
    expect(source, contains('final class Users extends TableRef<Users> {'));
    expect(source, contains("const Users._() : super('users');"));
    expect(source, contains('static const table = Users._();'));
    expect(
      source,
      contains(
          columnDecl('id', 'PrimaryKey<int, Users>', 'id', 'IntSqlType()')),
    );
    expect(
      source,
      contains(columnDecl(
        'bio',
        'ValueColumn<String?, Users>',
        'bio',
        'NullableSqlType(StringSqlType())',
      )),
    );
    expect(source, contains('final class Posts extends TableRef<Posts> {'));
    expect(
      source,
      contains(columnDecl(
        'authorId',
        'Ref<int, Posts, Users>',
        'author_id',
        'IntSqlType()',
        references: 'Users.id',
      )),
    );
    expect(
      source,
      contains(
        'List<TableColumn<Object?, Object?>> get columns => '
        'const [id, authorId, title];',
      ),
    );

    // It must NOT generate data classes — only the schema.
    expect(source, isNot(contains('class User ')));
    expect(source, isNot(contains('RowReader')));
  });

  test('generate-schema CLI writes to schema_output from --config', () async {
    final tmp = Directory.systemTemp.createTempSync('basalt_cli_schema_test');
    addTearDown(() => tmp.deleteSync(recursive: true));

    final dbPath = p.join(tmp.path, 'test.db');
    final schemaPath = p.join(tmp.path, 'out', 'schema.dart');
    final configPath = p.join(tmp.path, 'basalt.yaml');
    File(configPath).writeAsStringSync('''
backend: basalt_sqlite
database:
  path: $dbPath
schema_output: $schemaPath
''');

    final fileDb = SqliteConnection.open(dbPath);
    await fileDb.executeSql('CREATE TABLE widgets ('
        'id INTEGER NOT NULL PRIMARY KEY, '
        'name TEXT NOT NULL)');
    await fileDb.close();

    final code = await const CliRunner(SqliteAdapter()).build().run([
      '--config',
      configPath,
      'generate-schema',
    ]);
    expect(code, 0);

    final schema = File(schemaPath);
    expect(schema.existsSync(), isTrue);
    expect(
      schema.readAsStringSync(),
      contains('final class Widgets extends TableRef<Widgets> {'),
    );
    expect(
      schema.readAsStringSync(),
      contains(
        '// GENERATED by `basalt generate-schema`. Do not edit by hand.',
      ),
    );
  });

  group('type overrides', () {
    test('by column: emits the exact type and adds the import', () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byColumn: {
            'users.bio': TypeOverride(
              dartType: 'Html',
              sqlType: 'HtmlSqlType()',
              import: 'package:x/html.dart',
            ),
          },
        ),
      ).generate(await db.introspect());

      // bio is nullable, so the override is wrapped automatically.
      expect(
        source,
        contains(columnDecl(
          'bio',
          'ValueColumn<Html?, Users>',
          'bio',
          'NullableSqlType(HtmlSqlType())',
        )),
      );
      expect(
        source,
        contains("import 'package:basalt/basalt.dart';\n"
            "import 'package:x/html.dart';"),
      );
    });

    test('by native type: matches rawType, no import when none given',
        () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byNative: {
            'text': TypeOverride(dartType: 'Slug', sqlType: 'SlugSqlType()'),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(
          columnDecl(
              'name', 'ValueColumn<Slug, Users>', 'name', 'SlugSqlType()'),
        ),
      );
      // Only the basalt import — the override supplied none.
      expect("import '".allMatches(source).length, 1);
    });

    test('by canonical type: applies to value, PK and FK columns', () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byCanonical: {
            ColumnType.integer:
                TypeOverride(dartType: 'Count', sqlType: 'CountSqlType()'),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(
          columnDecl(
              'age', 'ValueColumn<Count, Users>', 'age', 'CountSqlType()'),
        ),
      );
      expect(
        source,
        contains(
          columnDecl('id', 'PrimaryKey<Count, Users>', 'id', 'CountSqlType()'),
        ),
      );
      expect(
        source,
        contains(columnDecl(
          'authorId',
          'Ref<Count, Posts, Users>',
          'author_id',
          'CountSqlType()',
          references: 'Users.id',
        )),
      );
    });

    test('precedence: specific column wins over native and canonical',
        () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byColumn: {
            'users.name':
                TypeOverride(dartType: 'ColName', sqlType: 'ColNameSqlType()'),
          },
          byNative: {
            'text':
                TypeOverride(dartType: 'NatText', sqlType: 'NatTextSqlType()'),
          },
          byCanonical: {
            ColumnType.text:
                TypeOverride(dartType: 'CanText', sqlType: 'CanTextSqlType()'),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(columnDecl(
          'name',
          'ValueColumn<ColName, Users>',
          'name',
          'ColNameSqlType()',
        )),
      );
      // title (text, no column override) falls through to the native override.
      expect(
        source,
        contains(columnDecl(
          'title',
          'ValueColumn<NatText, Posts>',
          'title',
          'NatTextSqlType()',
        )),
      );
    });

    test('nullable columns derive the wrapped variant from one override',
        () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byNative: {
            'text': TypeOverride(dartType: 'Slug', sqlType: 'SlugSqlType()'),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(
          columnDecl(
              'name', 'ValueColumn<Slug, Users>', 'name', 'SlugSqlType()'),
        ),
      );
      expect(
        source,
        contains(columnDecl(
          'bio',
          'ValueColumn<Slug?, Users>',
          'bio',
          'NullableSqlType(SlugSqlType())',
        )),
      );
    });

    test('imports are de-duplicated and sorted', () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byColumn: {
            'users.name': TypeOverride(
              dartType: 'A',
              sqlType: 'ASqlType()',
              import: 'package:z/z.dart',
            ),
            'users.bio': TypeOverride(
              dartType: 'A?',
              sqlType: 'AOrNull()',
              import: 'package:z/z.dart',
            ),
            'users.age': TypeOverride(
              dartType: 'B',
              sqlType: 'BSqlType()',
              import: 'package:a/a.dart',
            ),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains("import 'package:basalt/basalt.dart';\n"
            "import 'package:a/a.dart';\n"
            "import 'package:z/z.dart';"),
      );
      expect("import 'package:z/z.dart'".allMatches(source).length, 1);
    });

    test('Ref/PrimaryKey type disagreement throws StateError', () async {
      final tables = await db.introspect();
      expect(
        () => const SchemaGenerator(
          typeOverrides: SchemaTypeOverrides(
            byColumn: {
              'posts.author_id': TypeOverride(
                dartType: 'WidgetId',
                sqlType: 'WidgetIdSqlType()',
              ),
            },
          ),
        ).generate(tables),
        throwsStateError,
      );
    });
  });

  group('adapter type presets through the CLI', () {
    late Directory tmp;
    late String configPath;
    late String schemaPath;

    setUp(() async {
      tmp = Directory.systemTemp.createTempSync('basalt_preset_test');
      addTearDown(() => tmp.deleteSync(recursive: true));
      schemaPath = p.join(tmp.path, 'schema.dart');
      configPath = p.join(tmp.path, 'basalt.yaml');

      // Declared BOOLEAN/DATETIME collapse to INTEGER affinity, but the
      // declared type survives in rawType — which the sqlite preset keys on.
      final fileDb = SqliteConnection.open(p.join(tmp.path, 'test.db'));
      await fileDb.executeSql('CREATE TABLE events ('
          'id INTEGER NOT NULL PRIMARY KEY, '
          'active BOOLEAN NOT NULL, '
          'starts_at DATETIME NOT NULL, '
          'ends_at DATETIME)');
      await fileDb.close();
    });

    Future<String> generate(String config) async {
      File(configPath).writeAsStringSync(config);
      final code = await const CliRunner(SqliteAdapter())
          .build()
          .run(['--config', configPath, 'generate-schema']);
      expect(code, 0);
      return File(schemaPath).readAsStringSync();
    }

    test('sqlite preset restores bool/DateTime from declared types', () async {
      final source = await generate('''
backend: basalt_sqlite
database:
  path: ${p.join(tmp.path, 'test.db')}
schema_output: $schemaPath
''');
      expect(
        source,
        contains(columnDecl(
          'active',
          'ValueColumn<bool, Events>',
          'active',
          'BooleanSqlType()',
        )),
      );
      expect(
        source,
        contains(columnDecl(
          'startsAt',
          'ValueColumn<DateTime, Events>',
          'starts_at',
          'DateTimeSqlType()',
        )),
      );
      // Nullable column gets the wrapped variant.
      expect(
        source,
        contains(columnDecl(
          'endsAt',
          'ValueColumn<DateTime?, Events>',
          'ends_at',
          'NullableSqlType(DateTimeSqlType())',
        )),
      );
    });

    test('user types: override beats the preset', () async {
      final source = await generate('''
backend: basalt_sqlite
database:
  path: ${p.join(tmp.path, 'test.db')}
schema_output: $schemaPath
types:
  native:
    boolean: { dart_type: "MyFlag", sql_type: "MyFlagSqlType()" }
''');
      expect(source, contains("'active',\n    MyFlagSqlType(),"));
      // The preset still applies where the user didn't override.
      expect(source, contains("'starts_at',\n    DateTimeSqlType(),"));
    });

    test('native_types: true layers the native tier over the portable one',
        () async {
      // SqliteAdapter's native tier is empty, so exercise the gate with the
      // postgres-style shape: a stub adapter whose native tier retypes
      // DATETIME differently from its portable tier.
      final baseConfig = '''
backend: basalt_sqlite
database:
  path: ${p.join(tmp.path, 'test.db')}
schema_output: $schemaPath
''';

      File(configPath).writeAsStringSync(baseConfig);
      final code = await const CliRunner(_NativeTierAdapter())
          .build()
          .run(['--config', configPath, 'generate-schema']);
      expect(code, 0);
      final withoutOptIn = File(schemaPath).readAsStringSync();
      expect(withoutOptIn, contains("'starts_at',\n    PortableSqlType(),"));

      File(configPath).writeAsStringSync('${baseConfig}native_types: true\n');
      final optedIn = await const CliRunner(_NativeTierAdapter())
          .build()
          .run(['--config', configPath, 'generate-schema']);
      expect(optedIn, 0);
      final withOptIn = File(schemaPath).readAsStringSync();
      expect(withOptIn, contains("'starts_at',\n    NativeSqlType(),"));
    });
  });
}

/// Stub adapter with distinct portable and native preset tiers, to verify the
/// `native_types:` gate and tier precedence end-to-end.
final class _NativeTierAdapter extends BasaltAdapter {
  const _NativeTierAdapter();

  @override
  String get name => 'stub';

  @override
  Future<Connection> open(Map<String, Object?> options) =>
      const SqliteAdapter().open(options);

  @override
  Future<void> reset(Map<String, Object?> options) =>
      const SqliteAdapter().reset(options);

  @override
  SchemaTypeOverrides get typeOverrides => const SchemaTypeOverrides(
        byNative: {
          'datetime': TypeOverride(
            dartType: 'Portable',
            sqlType: 'PortableSqlType()',
          ),
        },
      );

  @override
  SchemaTypeOverrides get nativeTypeOverrides => const SchemaTypeOverrides(
        byNative: {
          'datetime': TypeOverride(
            dartType: 'Native',
            sqlType: 'NativeSqlType()',
          ),
        },
      );
}
