import 'dart:io';

import 'package:basalt/basalt.dart';
import 'package:basalt_cli/basalt_cli.dart';
import 'package:basalt_sqlite/basalt_sqlite.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  late SqliteConnection db;

  setUp(() async {
    db = SqliteConnection.memory();
    await db.executeSql('CREATE TABLE users ('
        'id INTEGER NOT NULL PRIMARY KEY, '
        'name TEXT NOT NULL, '
        'bio TEXT, ' // nullable
        'age INTEGER NOT NULL)');
    await db.executeSql('CREATE TABLE posts ('
        'id INTEGER NOT NULL PRIMARY KEY, '
        'author_id INTEGER NOT NULL REFERENCES users(id), '
        'title TEXT NOT NULL)');
  });

  tearDown(() => db.close());

  test('introspect reads tables, columns, nullability, pk and fks', () async {
    final tables = await db.introspect();
    expect(tables.map((t) => t.name), ['posts', 'users']); // sorted

    final users = tables.firstWhere((t) => t.name == 'users');
    final id = users.columns.firstWhere((c) => c.name == 'id');
    expect(id.isPrimaryKey, isTrue);
    expect(id.isNullable, isFalse);
    final bio = users.columns.firstWhere((c) => c.name == 'bio');
    expect(bio.isNullable, isTrue);

    final posts = tables.firstWhere((t) => t.name == 'posts');
    final authorId = posts.columns.firstWhere((c) => c.name == 'author_id');
    expect(authorId.foreignKey?.table, 'users');
    expect(authorId.foreignKey?.column, 'id');
  });

  test('generateSchema emits tables-only Dart (no data classes)', () async {
    final source = const SchemaGenerator().generate(await db.introspect());

    expect(source, contains("import 'package:basalt/basalt.dart';"));
    expect(source, contains('abstract final class Users {'));
    expect(
      source,
      contains(
        "static const id = PrimaryKey<int, Users>('users', 'id', IntSqlType());",
      ),
    );
    expect(
      source,
      contains(
        "static const bio = ValueColumn<String?, Users>('users', 'bio', StringOrNullSqlType());",
      ),
    );
    expect(source, contains('abstract final class Posts {'));
    expect(
      source,
      contains('static const authorId = Ref<int, Posts, Users>('
          "'posts', 'author_id', IntSqlType(), references: Users.id);"),
    );
    expect(
      source,
      contains(
        "static const table = TableRef<Posts>('posts', [id, authorId, title]);",
      ),
    );

    // It must NOT generate data classes — only the schema.
    expect(source, isNot(contains('class User ')));
    expect(source, isNot(contains('RowReader')));
  });

  test('generate-schema CLI writes to schema_output from --config', () async {
    final tmp = Directory.systemTemp.createTempSync('basalt_cli_schema_test');
    addTearDown(() => tmp.deleteSync(recursive: true));

    final dbPath = p.join(tmp.path, 'test.db');
    final schemaPath = p.join(tmp.path, 'out', 'schema.dart');
    final configPath = p.join(tmp.path, 'basalt.yaml');
    File(configPath).writeAsStringSync('''
database_url: $dbPath
schema_output: $schemaPath
''');

    final fileDb = SqliteConnection.open(dbPath);
    await fileDb.executeSql('CREATE TABLE widgets ('
        'id INTEGER NOT NULL PRIMARY KEY, '
        'name TEXT NOT NULL)');
    await fileDb.close();

    final code = await const CliRunner().build().run([
      '--config',
      configPath,
      'generate-schema',
    ]);
    expect(code, 0);

    final schema = File(schemaPath);
    expect(schema.existsSync(), isTrue);
    expect(
      schema.readAsStringSync(),
      contains('abstract final class Widgets {'),
    );
    expect(
      schema.readAsStringSync(),
      contains(
        '// GENERATED by `basalt generate-schema`. Do not edit by hand.',
      ),
    );
  });

  group('type overrides', () {
    test('by column: emits the exact type and adds the import', () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byColumn: {
            'users.bio': TypeOverride(
              dartType: 'Html?',
              sqlType: 'HtmlSqlType()',
              import: 'package:x/html.dart',
            ),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(
          "static const bio = ValueColumn<Html?, Users>('users', 'bio', HtmlSqlType());",
        ),
      );
      expect(
        source,
        contains("import 'package:basalt/basalt.dart';\n"
            "import 'package:x/html.dart';"),
      );
    });

    test('by native type: matches rawType, no import when none given',
        () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byNative: {
            'text': TypeOverride(dartType: 'Slug', sqlType: 'SlugSqlType()'),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(
          "static const name = ValueColumn<Slug, Users>('users', 'name', SlugSqlType());",
        ),
      );
      // Only the basalt import — the override supplied none.
      expect("import '".allMatches(source).length, 1);
    });

    test('by canonical type: applies to value, PK and FK columns', () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byCanonical: {
            ColumnType.integer:
                TypeOverride(dartType: 'Count', sqlType: 'CountSqlType()'),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(
          "static const age = ValueColumn<Count, Users>('users', 'age', CountSqlType());",
        ),
      );
      expect(
        source,
        contains(
          "static const id = PrimaryKey<Count, Users>('users', 'id', CountSqlType());",
        ),
      );
      expect(
        source,
        contains(
          "static const authorId = Ref<Count, Posts, Users>('posts', 'author_id', CountSqlType(), references: Users.id);",
        ),
      );
    });

    test('precedence: specific column wins over native and canonical',
        () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byColumn: {
            'users.name':
                TypeOverride(dartType: 'ColName', sqlType: 'ColNameSqlType()'),
          },
          byNative: {
            'text':
                TypeOverride(dartType: 'NatText', sqlType: 'NatTextSqlType()'),
          },
          byCanonical: {
            ColumnType.text:
                TypeOverride(dartType: 'CanText', sqlType: 'CanTextSqlType()'),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(
          "static const name = ValueColumn<ColName, Users>('users', 'name', ColNameSqlType());",
        ),
      );
      // title (text, no column override) falls through to the native override.
      expect(
        source,
        contains(
          "static const title = ValueColumn<NatText, Posts>('posts', 'title', NatTextSqlType());",
        ),
      );
    });

    test('nullable columns use the nullable variant', () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byNative: {
            'text': TypeOverride(dartType: 'Slug', sqlType: 'SlugSqlType()'),
          },
          byNativeNullable: {
            'text':
                TypeOverride(dartType: 'Slug?', sqlType: 'SlugOrNullSqlType()'),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains(
          "static const name = ValueColumn<Slug, Users>('users', 'name', SlugSqlType());",
        ),
      );
      expect(
        source,
        contains(
          "static const bio = ValueColumn<Slug?, Users>('users', 'bio', SlugOrNullSqlType());",
        ),
      );
    });

    test('imports are de-duplicated and sorted', () async {
      final source = const SchemaGenerator(
        typeOverrides: SchemaTypeOverrides(
          byColumn: {
            'users.name': TypeOverride(
              dartType: 'A',
              sqlType: 'ASqlType()',
              import: 'package:z/z.dart',
            ),
            'users.bio': TypeOverride(
              dartType: 'A?',
              sqlType: 'AOrNull()',
              import: 'package:z/z.dart',
            ),
            'users.age': TypeOverride(
              dartType: 'B',
              sqlType: 'BSqlType()',
              import: 'package:a/a.dart',
            ),
          },
        ),
      ).generate(await db.introspect());

      expect(
        source,
        contains("import 'package:basalt/basalt.dart';\n"
            "import 'package:a/a.dart';\n"
            "import 'package:z/z.dart';"),
      );
      expect("import 'package:z/z.dart'".allMatches(source).length, 1);
    });

    test('Ref/PrimaryKey type disagreement throws StateError', () async {
      final tables = await db.introspect();
      expect(
        () => const SchemaGenerator(
          typeOverrides: SchemaTypeOverrides(
            byColumn: {
              'posts.author_id': TypeOverride(
                dartType: 'WidgetId',
                sqlType: 'WidgetIdSqlType()',
              ),
            },
          ),
        ).generate(tables),
        throwsStateError,
      );
    });
  });
}
