/// Emits the bootstrap entrypoint written to `.dart_tool/basalt/entrypoint.dart`.
///
/// A pure string emitter (unit-testable without touching the filesystem): the
/// generated program imports the backend package's conventional
/// `lib/adapter.dart` and hands its top-level `adapter` constant to
/// `runBasalt` together with the original CLI arguments.
final class EntrypointGenerator {
  const EntrypointGenerator();

  /// The generated entrypoint source for [backendPackage].
  String generate({required String backendPackage}) => '''
// GENERATED by the basalt CLI (basalt_cli). Do not edit by hand.
//
// Bridges the CLI to the backend selected by `backend:` in basalt.yaml.
// Regenerated automatically when the backend or the package graph changes.
import 'dart:io';

import 'package:basalt_cli/basalt_cli.dart' as cli;
import 'package:$backendPackage/adapter.dart' as backend;

Future<void> main(List<String> args) async {
  exit(await cli.runBasalt(args, adapter: backend.adapter));
}
''';
}
